@startuml

component LayoutRouterContext
component IntlProvider

LayoutRouterContext -- IntlProvider

component ThemeProviderAdmin
component AdminRootLayout
component LoginLayout
component PagesLayout
component Login
component LoginPage
component LoginPageForm

component Admin
component AdminPage
component AdminPageForm

component Sites
component Settings
component Products
component Orders
component CategoryLayout

component Categories
component CreateCategory
component CreateSubCategory
component UpdateSubCategory
component SubCategoryForm

component SitesPage
component CreateSite
component UpdateSite
component SiteForm

component SettingsPage

component UsersPage
component AddUser
component UpdateUser
component UserForm

component ProductsList
component CreateProduct
component UpdateProduct
component ProductForm

component OrdersList
component OrderDetailsPage
component OrderDetailsForm

IntlProvider -- ThemeProviderAdmin
ThemeProviderAdmin -- AdminRootLayout
AdminRootLayout -- LoginLayout
AdminRootLayout -- PagesLayout

LoginLayout -- Login
Login -- LoginPage
LoginPage -- LoginPageForm

PagesLayout -- Admin
PagesLayout -- Sites
PagesLayout -- Settings
PagesLayout -- Products
PagesLayout -- Orders
PagesLayout -- CategoryLayout

Admin -- AdminPage
AdminPage -- AdminPageForm

CategoryLayout -- Categories
CategoryLayout -- CreateCategory
CategoryLayout -- CreateSubCategory
CategoryLayout -- UpdateSubCategory

CreateSubCategory -- SubCategoryForm
UpdateSubCategory -- SubCategoryForm

Sites -- SitesPage
Sites -- CreateSite
Sites -- UpdateSite

CreateSite -- SiteForm
UpdateSite -- SiteForm

Settings -- SettingsPage
SettingsPage -- UsersPage
SettingsPage -- AddUser
SettingsPage -- UpdateUser

AddUser -- UserForm
UpdateUser -- UserForm

Products -- ProductsList
Products -- CreateProduct
Products -- UpdateProduct

CreateProduct -- ProductForm
UpdateProduct -- ProductForm

Orders -- OrdersList
Orders -- OrderDetailsPage
OrderDetailsPage -- OrderDetailsForm

@enduml