@startuml

component LayoutRouterContext
component IntlProvider

LayoutRouterContext -- IntlProvider

component ThemeProviderStorefront
component UserProvider
component RootLayout
component Header
component ContentLayout
component Footer

IntlProvider -- ThemeProviderStorefront
ThemeProviderStorefront -- UserProvider
UserProvider -- RootLayout
RootLayout -- Header
RootLayout -- ContentLayout
RootLayout -- Footer

component HomePage
component CategoryPage
component ProductPage
component CartPage
component CheckoutSuccessPage

component ProductList
component CartForm

ContentLayout -- HomePage
ContentLayout -- CategoryPage
ContentLayout -- ProductPage
ContentLayout -- CartPage
ContentLayout -- CheckoutSuccessPage

HomePage -- ProductList
CategoryPage -- ProductList

CartPage - CartForm

@enduml