networks:
    internal:
        name: project-network

services:
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./db/redis:/root/redis
        expose:
            - 6379
    db:
        image: mysql
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: shop
            MYSQL_ROOT_PASSWORD: 'shop'
            # MYSQL_USER: 'root'
        volumes:
            - ./db/mysql:/var/lib/mysql
        ports:
            - 3307:3306
        expose:
            - 3307
