services:
    redis:
        container_name: redis
        image: redis:latest
        ports:
            - 6379:6379
        volumes:
            - ./db/redis:/root/redis
        expose:
            - 6379
        networks:
            - backend
    db:
        image: mysql
        container_name: db
        restart: always
        environment:
            MYSQL_DATABASE: shop
            MYSQL_ROOT_PASSWORD: 'shop'
        volumes:
            - ./db/mysql:/var/lib/mysql
        ports:
            - 3307:3306
        expose:
            - 3307
        networks:
            - backend

    backend:
        depends_on:
            - db
            - redis
        container_name: backend
        build:
            context: backend
            dockerfile: Dockerfile
        volumes:
            - ./backend/uploads:/usr/src/app/uploads
        networks:
            - backend
            - frontend

    frontend:
        depends_on:
            - backend
        container_name: frontend
        build:
            context: client
            dockerfile: Dockerfile
        networks:
            - frontend

    nginx-server:
        image: nginx
        depends_on:
            - frontend
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/certs:/etc/nginx/certs
        ports:
            - '443:443'
        networks:
            - frontend

networks:
    backend:
        driver: bridge
    frontend:
        driver: bridge
