import type { Metadata } from 'next';
import { Nunito } from 'next/font/google';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import '../../client/styles/globals.css';
import clsx from 'clsx';

const nunito = Nunito({ subsets: ['cyrillic'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    params,
}: Readonly<{
    children: React.ReactNode;
    params: { locale: string };
}>) {
    const messages = useMessages();

    return (
        <html lang={params.locale.split('-')[1].toLocaleLowerCase()}>
            <body className={clsx(nunito.className)}>
                <NextIntlClientProvider messages={messages}>
                    {children}
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
